version: '3.7'

services:

  chart-js-axis-plugin-demo-prod:
    image: chart.js.axis.plugin.demo.prod
    container_name: chart-js-axis-plugin-demo-prod 
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8877:80' 
