# build environment
FROM node:13.12.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . ./
RUN npm i
RUN npm run build
# need to set up webpack to create html in build so that this isnt necessary 
COPY build/index.html build/

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN apk add --no-cache bash
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]    
