import { ScriptableContext } from 'chart.js';
import { Data, ChartOpts, ColorOpts, ColorFunction } from '../../common/types';

const colorFunctions = {
  steppingHue: (
    context: ScriptableContext<'bar'>,
    data: Data,
    colorOpts: ColorOpts
  ): string => {
    const { baseHue, hueSpan } = colorOpts;
    const hueStepSize =
      hueSpan / data.datasets[context.datasetIndex].data.length;
    const hue = baseHue;
    const shadingIndex = context.dataIndex;
    return `hsl(${hue + hueStepSize * shadingIndex},100%,75%)`;
  },
  colorByScore: (context: ScriptableContext<'bar'>): string => {
    const maxRange = context.chart.scales.y.max - context.chart.scales.y.min;
    const gradingConstant = 100 / maxRange;
    const hue = gradingConstant * context.parsed.y;
    return `hsl(${gradingConstant * context.parsed.y},100%,50%)`;
  },
};
export const defaultOpts: ChartOpts = {
  colorOpts: {
    baseHue: 206,
    hueSpan: 30,
  },
  borderRadius: 4,
  colorFunction: colorFunctions.colorByScore,
};

export const exampleLabels = [
  'Old Tjikko',
  'Oliveira do Mouchão',
  'Stara Maslina',
  'Ballyconnell Yew',
  'Craigends Yew',
  'Fortingall Yew',
  'Florence Court Yew',
  'Bermiego Yew',
  "Caesarsboom (Caesar's Tree)",
  'Estry Yew',
  'La-Haye-de-Routot Yews',
  'Forest swastika',
  'The Old Elm',
  'Granit Oak',
  'Bartek',
  'Gernikako Arbola',
  'The Great Sequoia',
  'Queen Elizabeth Oak',
  'Darley Oak',
  'Kongeegen (the King Oak)',
  'Chêne chapelle',
  'Poltava Oak',
  'Stoke Gabriel Yew',
  'Major Oak',
  'Miraculous Mulberry from Dinoša',
  'Gilwell Oak',
  'Ivenack Oak',
  "Baikushev's pine",
  'Stelmužė Oak',
  'Chestnut Tree of One Hundred Horses',
  'Bialbero de Casorzo (Grana Double Tree)',
  'Le Gros chêne de Liernu (the big oak of Liernu)',
  'The Oaks of Rogalin',
  'The Olive tree of Vouves',
  'Mulberry of the Patriarchate of Peć',
  'Old Oak',
  'The Hungry Tree',
  'Divljana Oak',
  "Koča's oak",
  'Veliki Popovac oak',
  "Plane tree at Miloš's Residence",
  'Flower Square oak',
  "Brian Boru's Oak",
  'Pi de les Tres Branques',
  'Midland Oak',
  'Najevnik Linden Tree',
  'Tamme-Lauri oak',
  'Viiralti Oak',
  'Orissaare Stadium oak',
  "King's Pine",
  'Kelchi linden',
  'Waldtraut vom Mühlenwald',
  'Sobreiro Monumental',
  'Eucalipto do Vale de Canas',
  'Abies alba',
  'Fagus sylvatica',
  'Oak, Pedunculate',
  'Salix alba',
  'Acer campestre',
  'False-acacia',
  'Oak, Sessile',
  'Salix caprea',
  'Acer platanoides',
  'Field-rose',
  'Oak, Turkey',
  'Salix cinerea',
  'Acer pseudoplatanus',
  'Fir, Common',
  "Old-man's-beard",
  'Salix fragilis',
  'Aesculus hippocastanum',
  'Frangula alnus',
  'Osier',
  'Salix purpurea',
  'Alder',
  'Fraxinus excelsior',
  'Pear, Wild',
  'Salix x sepulcralis',
  'Alnus glutinosa',
  'Furze',
  'Picea abies',
  'Salix viminalis',
  'Apple, Crab',
  'Gorse',
  'Picea sitchensis',
  'Sambucus nigra',
  'Guelder-rose',
  'Pine, Austrian',
  'Sea-buckthorn',
  'Aspen',
  'Hawthorn',
  'Pine, Scots',
  'Service-tree, Wild',
  'Beech',
  'Hawthorn, Midland',
  'Pinus nigra',
  'Snowberry',
  'Betula pendula',
  'Hazel',
  'Pinus sylvestris',
  'Sorbus aria',
  'Betula pubescens',
  'Hedera helix',
  'Plane, London',
  'Sorbus aucuparia',
  'Birch, Downy',
  'Hippophae rhamnoides',
  'Platanus x hispanica',
  'Sorbus torminalis',
  'Birch, Silver',
  'Holly',
  'Plum, Cherry',
  'Spindle',
  'Blackthorn',
  'Honeysuckle',
  'Plum, Wild',
  'Spruce, Norway',
  'Hornbeam',
  'Poplar, Black',
  'Spruce, Sitka',
  'Broom',
  'Horse-chestnut',
  'Poplar, Grey',
  'Spurge-laurel',
  'Buckthorn, Alder',
  'Ilex aquifolium',
  'Poplar, Italian',
  'Sycamore',
  'Buckthorn, Purging',
  'Poplar, White',
  'Symphoricarpos albus',
  'Buddleia',
  'Juglans regia',
  'Populus alba',
  'Syringa vulgaris',
  'Buddleia davidii',
  'Juniper',
  'Populus canescens',
  'Taxus baccata',
  'Buxus sempervirens',
  'Juniperus communis ssp. communis',
  'Populus nigra',
  'Tilia cordata',
  'Carpinus betulus',
  'Laburnum',
  'Populus tremula',
  'Tilia x europaea',
  'Castanea sativa',
  'Laburnum anagyroides',
  'Populus x canadensis var. serotina',
  "Traveller's-joy",
  'Cherry, Bird',
  'Larch, European',
  'Privet, Wild',
  'Ulex europaeus',
  'Cherry, Dwarf',
  'Larix decidua',
  'Prunus avium',
  'Ulmus glabra',
  'Cherry, Wild',
  'Laurel, Cherry',
  'Prunus cerasifera',
  'Viburnum lantana',
  'Chestnut, Sweet see also Horse-chestnut',
  'Ligustrum vulgare',
  'Prunus cerasus',
  'Viburnum opulus',
  'Clematis vitalba',
  'Lilac',
  'Prunus domestica',
  'Walnut',
  'Cornus sanguinea',
  'Lime, Common',
  'Prunus laurocerasus',
  'Wayfaring-tree',
  'Corylus avellana',
  'Lime, Small-leaved',
  'Prunus padus',
  'Crataegus laevigata',
  'Lonicera periclymenum',
  'Prunus spinosa',
  'Whitebeam',
  'Crataegus monogyna',
  'Malus sylvestris ssp. sylvestris',
  'Pyrus communis',
  'Willow, Crack',
  'Cytisus scoparius',
  'Maple, Field',
  'Quercus cerris',
  'Willow, Goat',
  'Daphne laureola',
  'Maple, Norway',
  'Quercus petraea',
  'Willow, Grey',
  'Dog-rose',
  'Quercus robur',
  'Willow, Purple',
  'Dogwood',
  'Mountain-ash',
  'Rhamnus cathartica',
  'Willow, Weeping',
  'Elder',
  'Rhododendron',
  'Willow, White',
  'Elm, Wych',
  'Rhododendron ponticum',
  'Euonymus europaeus',
  'Robinia pseudoacacia',
  'Rosa arvensis',
  'Rosa canina',
  'Rose see Dog-rose or Field-rose',
  'Rowan',
];
